package com.example.demo.bean;

import java.io.Serializable;
import java.util.Date;

public class MMenu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.id
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.m_menu_number
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private String mMenuNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.m_menu_name
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private String mMenuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.create_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.create_time
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.update_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.update_time
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.del_flag
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_menu
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.id
     *
     * @return the value of m_menu.id
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.id
     *
     * @param id the value for m_menu.id
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.m_menu_number
     *
     * @return the value of m_menu.m_menu_number
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public String getmMenuNumber() {
        return mMenuNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.m_menu_number
     *
     * @param mMenuNumber the value for m_menu.m_menu_number
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setmMenuNumber(String mMenuNumber) {
        this.mMenuNumber = mMenuNumber == null ? null : mMenuNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.m_menu_name
     *
     * @return the value of m_menu.m_menu_name
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public String getmMenuName() {
        return mMenuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.m_menu_name
     *
     * @param mMenuName the value for m_menu.m_menu_name
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setmMenuName(String mMenuName) {
        this.mMenuName = mMenuName == null ? null : mMenuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.create_user
     *
     * @return the value of m_menu.create_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.create_user
     *
     * @param createUser the value for m_menu.create_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.create_time
     *
     * @return the value of m_menu.create_time
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.create_time
     *
     * @param createTime the value for m_menu.create_time
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.update_user
     *
     * @return the value of m_menu.update_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.update_user
     *
     * @param updateUser the value for m_menu.update_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.update_time
     *
     * @return the value of m_menu.update_time
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.update_time
     *
     * @param updateTime the value for m_menu.update_time
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.del_flag
     *
     * @return the value of m_menu.del_flag
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.del_flag
     *
     * @param delFlag the value for m_menu.del_flag
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}