package com.example.demo.bean;

import java.io.Serializable;
import java.util.Date;

public class MRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role.id
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role.m_role_name
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private String mRoleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role.m_role_number
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private String mRoleNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role.create_time
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role.create_user
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role.update_time
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role.update_user
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role.del_flag
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_role
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role.id
     *
     * @return the value of m_role.id
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role.id
     *
     * @param id the value for m_role.id
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role.m_role_name
     *
     * @return the value of m_role.m_role_name
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public String getmRoleName() {
        return mRoleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role.m_role_name
     *
     * @param mRoleName the value for m_role.m_role_name
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public void setmRoleName(String mRoleName) {
        this.mRoleName = mRoleName == null ? null : mRoleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role.m_role_number
     *
     * @return the value of m_role.m_role_number
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public String getmRoleNumber() {
        return mRoleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role.m_role_number
     *
     * @param mRoleNumber the value for m_role.m_role_number
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public void setmRoleNumber(String mRoleNumber) {
        this.mRoleNumber = mRoleNumber == null ? null : mRoleNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role.create_time
     *
     * @return the value of m_role.create_time
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role.create_time
     *
     * @param createTime the value for m_role.create_time
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role.create_user
     *
     * @return the value of m_role.create_user
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role.create_user
     *
     * @param createUser the value for m_role.create_user
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role.update_time
     *
     * @return the value of m_role.update_time
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role.update_time
     *
     * @param updateTime the value for m_role.update_time
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role.update_user
     *
     * @return the value of m_role.update_user
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role.update_user
     *
     * @param updateUser the value for m_role.update_user
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role.del_flag
     *
     * @return the value of m_role.del_flag
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role.del_flag
     *
     * @param delFlag the value for m_role.del_flag
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}