package com.example.demo.bean;

import java.io.Serializable;
import java.util.Date;

public class TDepartmentManager implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department_manager.id
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department_manager.name
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department_manager.type
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department_manager.create_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department_manager.create_time
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department_manager.update_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department_manager.update_time
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department_manager.del_flag
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department_manager.m_user_id
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private Integer mUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_department_manager
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department_manager.id
     *
     * @return the value of t_department_manager.id
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department_manager.id
     *
     * @param id the value for t_department_manager.id
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department_manager.name
     *
     * @return the value of t_department_manager.name
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department_manager.name
     *
     * @param name the value for t_department_manager.name
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department_manager.type
     *
     * @return the value of t_department_manager.type
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department_manager.type
     *
     * @param type the value for t_department_manager.type
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department_manager.create_user
     *
     * @return the value of t_department_manager.create_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department_manager.create_user
     *
     * @param createUser the value for t_department_manager.create_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department_manager.create_time
     *
     * @return the value of t_department_manager.create_time
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department_manager.create_time
     *
     * @param createTime the value for t_department_manager.create_time
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department_manager.update_user
     *
     * @return the value of t_department_manager.update_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department_manager.update_user
     *
     * @param updateUser the value for t_department_manager.update_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department_manager.update_time
     *
     * @return the value of t_department_manager.update_time
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department_manager.update_time
     *
     * @param updateTime the value for t_department_manager.update_time
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department_manager.del_flag
     *
     * @return the value of t_department_manager.del_flag
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department_manager.del_flag
     *
     * @param delFlag the value for t_department_manager.del_flag
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department_manager.m_user_id
     *
     * @return the value of t_department_manager.m_user_id
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public Integer getmUserId() {
        return mUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department_manager.m_user_id
     *
     * @param mUserId the value for t_department_manager.m_user_id
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setmUserId(Integer mUserId) {
        this.mUserId = mUserId;
    }
}