package com.example.demo.bean;

import java.util.ArrayList;
import java.util.List;

public class TDepartmentWorkerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_department_worker
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_department_worker
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_department_worker
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public TDepartmentWorkerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_department_worker
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTWorkNameIsNull() {
            addCriterion("t_work_name is null");
            return (Criteria) this;
        }

        public Criteria andTWorkNameIsNotNull() {
            addCriterion("t_work_name is not null");
            return (Criteria) this;
        }

        public Criteria andTWorkNameEqualTo(String value) {
            addCriterion("t_work_name =", value, "tWorkName");
            return (Criteria) this;
        }

        public Criteria andTWorkNameNotEqualTo(String value) {
            addCriterion("t_work_name <>", value, "tWorkName");
            return (Criteria) this;
        }

        public Criteria andTWorkNameGreaterThan(String value) {
            addCriterion("t_work_name >", value, "tWorkName");
            return (Criteria) this;
        }

        public Criteria andTWorkNameGreaterThanOrEqualTo(String value) {
            addCriterion("t_work_name >=", value, "tWorkName");
            return (Criteria) this;
        }

        public Criteria andTWorkNameLessThan(String value) {
            addCriterion("t_work_name <", value, "tWorkName");
            return (Criteria) this;
        }

        public Criteria andTWorkNameLessThanOrEqualTo(String value) {
            addCriterion("t_work_name <=", value, "tWorkName");
            return (Criteria) this;
        }

        public Criteria andTWorkNameLike(String value) {
            addCriterion("t_work_name like", value, "tWorkName");
            return (Criteria) this;
        }

        public Criteria andTWorkNameNotLike(String value) {
            addCriterion("t_work_name not like", value, "tWorkName");
            return (Criteria) this;
        }

        public Criteria andTWorkNameIn(List<String> values) {
            addCriterion("t_work_name in", values, "tWorkName");
            return (Criteria) this;
        }

        public Criteria andTWorkNameNotIn(List<String> values) {
            addCriterion("t_work_name not in", values, "tWorkName");
            return (Criteria) this;
        }

        public Criteria andTWorkNameBetween(String value1, String value2) {
            addCriterion("t_work_name between", value1, value2, "tWorkName");
            return (Criteria) this;
        }

        public Criteria andTWorkNameNotBetween(String value1, String value2) {
            addCriterion("t_work_name not between", value1, value2, "tWorkName");
            return (Criteria) this;
        }

        public Criteria andTWorkTelIsNull() {
            addCriterion("t_work_tel is null");
            return (Criteria) this;
        }

        public Criteria andTWorkTelIsNotNull() {
            addCriterion("t_work_tel is not null");
            return (Criteria) this;
        }

        public Criteria andTWorkTelEqualTo(String value) {
            addCriterion("t_work_tel =", value, "tWorkTel");
            return (Criteria) this;
        }

        public Criteria andTWorkTelNotEqualTo(String value) {
            addCriterion("t_work_tel <>", value, "tWorkTel");
            return (Criteria) this;
        }

        public Criteria andTWorkTelGreaterThan(String value) {
            addCriterion("t_work_tel >", value, "tWorkTel");
            return (Criteria) this;
        }

        public Criteria andTWorkTelGreaterThanOrEqualTo(String value) {
            addCriterion("t_work_tel >=", value, "tWorkTel");
            return (Criteria) this;
        }

        public Criteria andTWorkTelLessThan(String value) {
            addCriterion("t_work_tel <", value, "tWorkTel");
            return (Criteria) this;
        }

        public Criteria andTWorkTelLessThanOrEqualTo(String value) {
            addCriterion("t_work_tel <=", value, "tWorkTel");
            return (Criteria) this;
        }

        public Criteria andTWorkTelLike(String value) {
            addCriterion("t_work_tel like", value, "tWorkTel");
            return (Criteria) this;
        }

        public Criteria andTWorkTelNotLike(String value) {
            addCriterion("t_work_tel not like", value, "tWorkTel");
            return (Criteria) this;
        }

        public Criteria andTWorkTelIn(List<String> values) {
            addCriterion("t_work_tel in", values, "tWorkTel");
            return (Criteria) this;
        }

        public Criteria andTWorkTelNotIn(List<String> values) {
            addCriterion("t_work_tel not in", values, "tWorkTel");
            return (Criteria) this;
        }

        public Criteria andTWorkTelBetween(String value1, String value2) {
            addCriterion("t_work_tel between", value1, value2, "tWorkTel");
            return (Criteria) this;
        }

        public Criteria andTWorkTelNotBetween(String value1, String value2) {
            addCriterion("t_work_tel not between", value1, value2, "tWorkTel");
            return (Criteria) this;
        }

        public Criteria andTWorkTypeIsNull() {
            addCriterion("t_work_type is null");
            return (Criteria) this;
        }

        public Criteria andTWorkTypeIsNotNull() {
            addCriterion("t_work_type is not null");
            return (Criteria) this;
        }

        public Criteria andTWorkTypeEqualTo(String value) {
            addCriterion("t_work_type =", value, "tWorkType");
            return (Criteria) this;
        }

        public Criteria andTWorkTypeNotEqualTo(String value) {
            addCriterion("t_work_type <>", value, "tWorkType");
            return (Criteria) this;
        }

        public Criteria andTWorkTypeGreaterThan(String value) {
            addCriterion("t_work_type >", value, "tWorkType");
            return (Criteria) this;
        }

        public Criteria andTWorkTypeGreaterThanOrEqualTo(String value) {
            addCriterion("t_work_type >=", value, "tWorkType");
            return (Criteria) this;
        }

        public Criteria andTWorkTypeLessThan(String value) {
            addCriterion("t_work_type <", value, "tWorkType");
            return (Criteria) this;
        }

        public Criteria andTWorkTypeLessThanOrEqualTo(String value) {
            addCriterion("t_work_type <=", value, "tWorkType");
            return (Criteria) this;
        }

        public Criteria andTWorkTypeLike(String value) {
            addCriterion("t_work_type like", value, "tWorkType");
            return (Criteria) this;
        }

        public Criteria andTWorkTypeNotLike(String value) {
            addCriterion("t_work_type not like", value, "tWorkType");
            return (Criteria) this;
        }

        public Criteria andTWorkTypeIn(List<String> values) {
            addCriterion("t_work_type in", values, "tWorkType");
            return (Criteria) this;
        }

        public Criteria andTWorkTypeNotIn(List<String> values) {
            addCriterion("t_work_type not in", values, "tWorkType");
            return (Criteria) this;
        }

        public Criteria andTWorkTypeBetween(String value1, String value2) {
            addCriterion("t_work_type between", value1, value2, "tWorkType");
            return (Criteria) this;
        }

        public Criteria andTWorkTypeNotBetween(String value1, String value2) {
            addCriterion("t_work_type not between", value1, value2, "tWorkType");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("create_time like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("create_time not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("update_time like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("update_time not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(String value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(String value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(String value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(String value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(String value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(String value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLike(String value) {
            addCriterion("del_flag like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotLike(String value) {
            addCriterion("del_flag not like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<String> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<String> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(String value1, String value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(String value1, String value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andManagerIdIsNull() {
            addCriterion("manager_Id is null");
            return (Criteria) this;
        }

        public Criteria andManagerIdIsNotNull() {
            addCriterion("manager_Id is not null");
            return (Criteria) this;
        }

        public Criteria andManagerIdEqualTo(String value) {
            addCriterion("manager_Id =", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdNotEqualTo(String value) {
            addCriterion("manager_Id <>", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdGreaterThan(String value) {
            addCriterion("manager_Id >", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdGreaterThanOrEqualTo(String value) {
            addCriterion("manager_Id >=", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdLessThan(String value) {
            addCriterion("manager_Id <", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdLessThanOrEqualTo(String value) {
            addCriterion("manager_Id <=", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdLike(String value) {
            addCriterion("manager_Id like", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdNotLike(String value) {
            addCriterion("manager_Id not like", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdIn(List<String> values) {
            addCriterion("manager_Id in", values, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdNotIn(List<String> values) {
            addCriterion("manager_Id not in", values, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdBetween(String value1, String value2) {
            addCriterion("manager_Id between", value1, value2, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdNotBetween(String value1, String value2) {
            addCriterion("manager_Id not between", value1, value2, "managerId");
            return (Criteria) this;
        }

        public Criteria andTWorkAddressIsNull() {
            addCriterion("t_work_address is null");
            return (Criteria) this;
        }

        public Criteria andTWorkAddressIsNotNull() {
            addCriterion("t_work_address is not null");
            return (Criteria) this;
        }

        public Criteria andTWorkAddressEqualTo(String value) {
            addCriterion("t_work_address =", value, "tWorkAddress");
            return (Criteria) this;
        }

        public Criteria andTWorkAddressNotEqualTo(String value) {
            addCriterion("t_work_address <>", value, "tWorkAddress");
            return (Criteria) this;
        }

        public Criteria andTWorkAddressGreaterThan(String value) {
            addCriterion("t_work_address >", value, "tWorkAddress");
            return (Criteria) this;
        }

        public Criteria andTWorkAddressGreaterThanOrEqualTo(String value) {
            addCriterion("t_work_address >=", value, "tWorkAddress");
            return (Criteria) this;
        }

        public Criteria andTWorkAddressLessThan(String value) {
            addCriterion("t_work_address <", value, "tWorkAddress");
            return (Criteria) this;
        }

        public Criteria andTWorkAddressLessThanOrEqualTo(String value) {
            addCriterion("t_work_address <=", value, "tWorkAddress");
            return (Criteria) this;
        }

        public Criteria andTWorkAddressLike(String value) {
            addCriterion("t_work_address like", value, "tWorkAddress");
            return (Criteria) this;
        }

        public Criteria andTWorkAddressNotLike(String value) {
            addCriterion("t_work_address not like", value, "tWorkAddress");
            return (Criteria) this;
        }

        public Criteria andTWorkAddressIn(List<String> values) {
            addCriterion("t_work_address in", values, "tWorkAddress");
            return (Criteria) this;
        }

        public Criteria andTWorkAddressNotIn(List<String> values) {
            addCriterion("t_work_address not in", values, "tWorkAddress");
            return (Criteria) this;
        }

        public Criteria andTWorkAddressBetween(String value1, String value2) {
            addCriterion("t_work_address between", value1, value2, "tWorkAddress");
            return (Criteria) this;
        }

        public Criteria andTWorkAddressNotBetween(String value1, String value2) {
            addCriterion("t_work_address not between", value1, value2, "tWorkAddress");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_department_worker
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 31 09:02:20 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_department_worker
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}