package com.example.demo.bean;

import java.io.Serializable;
import java.util.Date;

public class TLargeArea implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_large_area.id
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_large_area.large_area_name
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private String largeAreaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_large_area.large_area_id
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private Integer largeAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_large_area.create_time
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_large_area.create_user
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_large_area.update_user
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_large_area.update_time
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_large_area.del_flag
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_large_area
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_large_area.id
     *
     * @return the value of t_large_area.id
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_large_area.id
     *
     * @param id the value for t_large_area.id
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_large_area.large_area_name
     *
     * @return the value of t_large_area.large_area_name
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public String getLargeAreaName() {
        return largeAreaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_large_area.large_area_name
     *
     * @param largeAreaName the value for t_large_area.large_area_name
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public void setLargeAreaName(String largeAreaName) {
        this.largeAreaName = largeAreaName == null ? null : largeAreaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_large_area.large_area_id
     *
     * @return the value of t_large_area.large_area_id
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public Integer getLargeAreaId() {
        return largeAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_large_area.large_area_id
     *
     * @param largeAreaId the value for t_large_area.large_area_id
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public void setLargeAreaId(Integer largeAreaId) {
        this.largeAreaId = largeAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_large_area.create_time
     *
     * @return the value of t_large_area.create_time
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_large_area.create_time
     *
     * @param createTime the value for t_large_area.create_time
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_large_area.create_user
     *
     * @return the value of t_large_area.create_user
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_large_area.create_user
     *
     * @param createUser the value for t_large_area.create_user
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_large_area.update_user
     *
     * @return the value of t_large_area.update_user
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_large_area.update_user
     *
     * @param updateUser the value for t_large_area.update_user
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_large_area.update_time
     *
     * @return the value of t_large_area.update_time
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_large_area.update_time
     *
     * @param updateTime the value for t_large_area.update_time
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_large_area.del_flag
     *
     * @return the value of t_large_area.del_flag
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_large_area.del_flag
     *
     * @param delFlag the value for t_large_area.del_flag
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}