package com.example.demo.mapper;

import com.example.demo.bean.MCity;
import com.example.demo.bean.MCityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_city
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int countByExample(MCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_city
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int deleteByExample(MCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_city
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int insert(MCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_city
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int insertSelective(MCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_city
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    List<MCity> selectByExample(MCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_city
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") MCity record, @Param("example") MCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_city
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int updateByExample(@Param("record") MCity record, @Param("example") MCityExample example);
}