package com.example.demo.mapper;

import com.example.demo.bean.MMenu;
import com.example.demo.bean.MMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int countByExample(MMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int deleteByExample(MMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int insert(MMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int insertSelective(MMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    List<MMenu> selectByExample(MMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") MMenu record, @Param("example") MMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int updateByExample(@Param("record") MMenu record, @Param("example") MMenuExample example);
}