package com.example.demo.mapper;

import com.example.demo.bean.MUser;
import com.example.demo.bean.MUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int countByExample(MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int deleteByExample(MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int insert(MUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int insertSelective(MUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    List<MUser> selectByExample(MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") MUser record, @Param("example") MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int updateByExample(@Param("record") MUser record, @Param("example") MUserExample example);
}