package com.example.demo.mapper;

import com.example.demo.bean.MUserMenu;
import com.example.demo.bean.MUserMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MUserMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_menu
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int countByExample(MUserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_menu
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int deleteByExample(MUserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_menu
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int insert(MUserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_menu
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int insertSelective(MUserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_menu
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    List<MUserMenu> selectByExample(MUserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_menu
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") MUserMenu record, @Param("example") MUserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_menu
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int updateByExample(@Param("record") MUserMenu record, @Param("example") MUserMenuExample example);
}