package com.example.demo.mapper;

import com.example.demo.bean.TDepartmentFundesigner;
import com.example.demo.bean.TDepartmentFundesignerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDepartmentFundesignerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_fundesigner
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int countByExample(TDepartmentFundesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_fundesigner
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int deleteByExample(TDepartmentFundesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_fundesigner
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int insert(TDepartmentFundesigner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_fundesigner
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int insertSelective(TDepartmentFundesigner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_fundesigner
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    List<TDepartmentFundesigner> selectByExample(TDepartmentFundesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_fundesigner
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") TDepartmentFundesigner record, @Param("example") TDepartmentFundesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_fundesigner
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int updateByExample(@Param("record") TDepartmentFundesigner record, @Param("example") TDepartmentFundesignerExample example);
}