package com.example.demo.mapper;

import com.example.demo.bean.TDepartmentWorker;
import com.example.demo.bean.TDepartmentWorkerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDepartmentWorkerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int countByExample(TDepartmentWorkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int deleteByExample(TDepartmentWorkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int insert(TDepartmentWorker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int insertSelective(TDepartmentWorker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    List<TDepartmentWorker> selectByExample(TDepartmentWorkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") TDepartmentWorker record, @Param("example") TDepartmentWorkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_worker
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int updateByExample(@Param("record") TDepartmentWorker record, @Param("example") TDepartmentWorkerExample example);
}