package com.example.demo.mapper;

import com.example.demo.bean.TDepartmentSales;
import com.example.demo.bean.TDepartmentSalesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDepartmentSalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_sales
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int countByExample(TDepartmentSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_sales
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int deleteByExample(TDepartmentSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_sales
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int insert(TDepartmentSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_sales
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int insertSelective(TDepartmentSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_sales
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    List<TDepartmentSales> selectByExample(TDepartmentSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_sales
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") TDepartmentSales record, @Param("example") TDepartmentSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_sales
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int updateByExample(@Param("record") TDepartmentSales record, @Param("example") TDepartmentSalesExample example);
}