package com.example.demo.mapper;

import com.example.demo.bean.TDepartmentSuper;
import com.example.demo.bean.TDepartmentSuperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDepartmentSuperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_super
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int countByExample(TDepartmentSuperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_super
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int deleteByExample(TDepartmentSuperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_super
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int insert(TDepartmentSuper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_super
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int insertSelective(TDepartmentSuper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_super
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    List<TDepartmentSuper> selectByExample(TDepartmentSuperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_super
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") TDepartmentSuper record, @Param("example") TDepartmentSuperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_super
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int updateByExample(@Param("record") TDepartmentSuper record, @Param("example") TDepartmentSuperExample example);
}