package com.example.demo.mapper;

import com.example.demo.bean.TDepartmentManager;
import com.example.demo.bean.TDepartmentManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDepartmentManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_manager
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int countByExample(TDepartmentManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_manager
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int deleteByExample(TDepartmentManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_manager
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int insert(TDepartmentManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_manager
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int insertSelective(TDepartmentManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_manager
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    List<TDepartmentManager> selectByExample(TDepartmentManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_manager
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") TDepartmentManager record, @Param("example") TDepartmentManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_manager
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int updateByExample(@Param("record") TDepartmentManager record, @Param("example") TDepartmentManagerExample example);
}