package com.example.demo.mapper;

import com.example.demo.bean.TDepartmentFinance;
import com.example.demo.bean.TDepartmentFinanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDepartmentFinanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_finance
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int countByExample(TDepartmentFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_finance
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int deleteByExample(TDepartmentFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_finance
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int insert(TDepartmentFinance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_finance
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int insertSelective(TDepartmentFinance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_finance
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    List<TDepartmentFinance> selectByExample(TDepartmentFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_finance
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") TDepartmentFinance record, @Param("example") TDepartmentFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_finance
     *
     * @mbggenerated Tue Aug 01 08:44:54 CST 2017
     */
    int updateByExample(@Param("record") TDepartmentFinance record, @Param("example") TDepartmentFinanceExample example);
}