package com.example.demo.mapper;

import com.example.demo.bean.TLargeArea;
import com.example.demo.bean.TLargeAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TLargeAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_large_area
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int countByExample(TLargeAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_large_area
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int deleteByExample(TLargeAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_large_area
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int insert(TLargeArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_large_area
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int insertSelective(TLargeArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_large_area
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    List<TLargeArea> selectByExample(TLargeAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_large_area
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") TLargeArea record, @Param("example") TLargeAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_large_area
     *
     * @mbggenerated Mon Jul 31 09:02:20 CST 2017
     */
    int updateByExample(@Param("record") TLargeArea record, @Param("example") TLargeAreaExample example);
}